# Generated by Django 5.2 on 2026-01-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_needs',
            field=models.TextField(blank=True, help_text='What are your main needs?', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_type',
            field=models.CharField(blank=True, help_text='Type of company/industry', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='va_tasks',
            field=models.TextField(blank=True, help_text='Tasks you want the VA to perform', null=True),
        ),
    ]
