# Generated by Django 5.2 on 2026-01-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_client_needs_customuser_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_zone',
            field=models.CharField(blank=True, help_text='Preferred Time Zone', max_length=100, null=True),
        ),
    ]
